name: Backend CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests + Build + PM2 restart
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print CI context (sanity)
        run: |
          node -v
          npm -v
          df -h | head -n 20

      - name: Stop running services in AWS (PM2)
        run: pm2 stop all || true

      # ---- Backend ----
      - name: Install backend deps (npm ci)
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: npm test

      # ---- Frontend ----
      - name: Install frontend deps and build (yarn)
        working-directory: ./frontend
        run: |
          sudo rm -rf ./build || true
          npm install --global yarn
          yarn --version
          yarn install
          yarn run build

      # ---- Write .env for production (prefer PROD if present) ----
      - name: Create backend .env for production
        working-directory: ./backend
        run: |
          if [ -n "${{ secrets.PROD }}" ]; then
            echo "${{ secrets.PROD }}" > .env
          else
            cat > .env <<'EOF'
            MONGO_URI=${{ secrets.MONGO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            PORT=${{ secrets.PORT }}
            EOF
          fi
          echo ".env written:"
          sed 's/=./=*hidden** /' .env || true

      # ---- Start / restart app under PM2 ----
      - name: Start/Restart PM2
        working-directory: ./backend
        run: |
          pm2 delete backend || true
          pm2 start "npm run start" --name "backend"
          pm2 save