name: Backend CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests + Build + PM2 restart
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Optional sanity check
      - name: Print CI context
        run: |
          node -v
          npm -v
          df -h | head -n 20

      - name: Stop running services in AWS (PM2)
        run: pm2 stop all || true

      # Backend install
      - name: Install backend deps (npm install)
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        working-directory: ./backend
        run: npm test

      # Frontend install & build
      - name: Install frontend deps and build (yarn)
        working-directory: ./frontend
        run: |
          sudo rm -rf ./build || true
          npm install --global yarn
          yarn --version
          yarn install
          yarn run build

      # Create .env for production
      - name: Create .env for production
        working-directory: ./backend
        env:
          PROD: ${{ secrets.PROD }}
        run: |
          if [ -n "${PROD}" ]; then
            echo "${PROD}" > .env
            echo ".env created from PROD secret"
          else
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo ".env created from individual secrets"
          fi

      # Start / restart PM2
      - name: Start/Restart PM2
        working-directory: ./backend
        run: |
          pm2 delete backend || true
          pm2 start "npm run start" --name "backend"
          pm2 save