name: Backend CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests + Build + PM2 restart
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Print CI context (sanity)
        run: |
          node -v
          npm -v
          df -h | head -n 20

      - name: Stop running services in AWS (PM2)
        run: pm2 stop all || true

      # --- Backend ---
      - name: Install backend deps
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: npm test

      # --- Frontend ---
      - name: Install frontend deps and build
        working-directory: ./frontend
        run: |
          rm -rf ./build || true
          npm install --global yarn
          yarn --version
          yarn install
          yarn run build

      # --- Create backend .env (prefer single PROD secret if present) ---
      - name: Create .env (use PROD if set)
        working-directory: ./backend
        env:
          PROD: ${{ secrets.PROD }}
        run: |
          if [ -n "${PROD}" ]; then
            echo "${PROD}" > .env
            echo ".env created from PROD secret"
          else
            cat > .env <<'EOF'
            MONGO_URI=${{ secrets.MONGO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            PORT=${{ secrets.PORT }}
            EOF
            echo ".env created from individual secrets"
          fi
          echo "----- .env preview (keys only) -----"
          sed -E 's/=.*/=<redacted>/' .env || true

      # --- PM2 start/restart ---
      - name: Start / Restart PM2
        working-directory: ./backend
        run: |
          pm2 delete backend || true
          pm2 start "npm run start" --name "backend"
          pm2 save